version: '3'

services:

  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose:
      - "3306"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    env_file: .env
    restart: always
    ports:
      - "443:443"

  wordpress:
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    expose:
      - "9000"

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/zool/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/zool/data/wordpress'